### ISSUE TITLE
Create `read` service for `Blog` content type

### ISSUE THREAD

**Issue by davidlukac** [slovak-drupal-association/komunita.drupal.sk#13]
- [ ] REST service providing _read_ (C**R**UD) operations for blogs.
- [ ] JSON output
- [ ] pagination
- [ ] title
- [ ] teaser
- [ ] attachments
- [ ] author

Related issues:
- [ ] #14 (create, update)
- [ ] #16  (delete)
- [ ] #6 (blog template)

See also documentation for [author](../wiki/User-%28author%29) and [blog](../wiki/Blog-content-type).

**Comment by miromichalicka** [comment]
Author will be probably another object with following fields:
- [ ] name
- [ ] surname
- [ ] uid
